# Generated by Django 5.2.8 on 2025-11-27 22:10

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0003_alter_folder_options_alter_pdf_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pdf',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdf',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pdf',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pdf',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pdf',
            name='last_viewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdf',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='pdf',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pdf',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['owner', '-updated_at'], name='folders_fol_owner_i_23e883_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['deleted_at'], name='folders_fol_deleted_b0830a_idx'),
        ),
        migrations.AddIndex(
            model_name='pdf',
            index=models.Index(fields=['folder', '-uploaded_at'], name='folders_pdf_folder__d960d6_idx'),
        ),
        migrations.AddIndex(
            model_name='pdf',
            index=models.Index(fields=['deleted_at'], name='folders_pdf_deleted_c76649_idx'),
        ),
        migrations.AddIndex(
            model_name='pdf',
            index=models.Index(fields=['-last_viewed'], name='folders_pdf_last_vi_474434_idx'),
        ),
    ]
