# Generated by Django 5.2.8 on 2025-11-28 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0004_folder_deleted_at_folder_share_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderLibraryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('custom_name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('username_slug', models.SlugField(blank=True, unique=True)),
                ('is_profile_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='folder',
            name='shared_with',
        ),
        migrations.AlterField(
            model_name='folder',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pdf',
            index=models.Index(fields=['is_public'], name='folders_pdf_is_publ_ef5f5e_idx'),
        ),
        migrations.AddField(
            model_name='folderlibraryentry',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folders.folder'),
        ),
        migrations.AddField(
            model_name='folderlibraryentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folder',
            name='added_by',
            field=models.ManyToManyField(blank=True, related_name='library_folders', through='folders.FolderLibraryEntry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['is_public'], name='folders_fol_is_publ_8eacdd_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['slug'], name='folders_fol_slug_f75275_idx'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='folderlibraryentry',
            index=models.Index(fields=['user', '-added_at'], name='folders_fol_user_id_9f09b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='folderlibraryentry',
            unique_together={('user', 'folder')},
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['username_slug'], name='folders_use_usernam_d596ee_idx'),
        ),
    ]
