# Generated by Django 5.2.8 on 2025-11-16 13:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Folder',
        ),
        migrations.RenameField(
            model_name='pdf',
            old_name='course',
            new_name='folder',
        ),
    ]
