# Generated by Django 5.2.8 on 2025-11-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_folder_is_public_alter_folder_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
