# Generated by Django 5.2.8 on 2025-11-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_pdf_file_alter_pdf_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='file',
            field=models.FileField(upload_to='pdfs/, max_length=1000'),
        ),
    ]
