# Generated by Django 5.2.8 on 2025-11-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='file',
            field=models.FileField(max_length=1000, upload_to='pdfs/'),
        ),
    ]
