# Generated by Django 5.2.8 on 2025-11-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscription_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
