# Generated by Django 5.2.8 on 2025-11-21 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pdf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PDF',
        ),
    ]
